GET http://localhost:3000/findNearest/fcc?address=66+Nanyang+Crescent
###
GET http://localhost:3000/findNearest/gym-and-park?address=66+Nanyang+Crescent
###
GET http://localhost:3000/findNearest/users?address=66+Nanyang+Crescent
