POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "test",
    "password": "asd"
}
###
DELETE http://localhost:3000/users
Content-Type: application/json

{
    "username": "Kai Jie",
    "password": "password"
}
###
PATCH http://localhost:3000/users
Content-Type: application/json

{
    "username": "Muthu",
    "password": "password",
    "name": "Muthu"
}

###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "username": "Jonathan",
    "password": "password",
    "name": "Jonathan",
    "birthdate": 946656000000,
    "residentialAddress": "48 Nanyang Cres",
    "currentAbilities": {
        "pushUpCount": 33,
        "sitUpCount": 35,
        "runTimeInSeconds": 740
    },
    "targetAbilities": {
        "pushUpCount": 60,
        "sitUpCount": 60,
        "runTimeInSeconds": 600
    }
}
###